---
title: "Uluslararası mutluluk farklılıkları"
author: 
  - ABDULLAH BARUT[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 18080656, [Github Repo](https://github.com/Abdullahbarut/arasinav)



# Giriş
Mutluluk, insan hayatında önemli bir yer tutar ve dünya genelinde insanların mutluluğu birçok ülke için önemli bir hedef haline gelmiştir. Ancak tüm ülkeler aynı mutluluk seviyesine sahip değiller ve bazı ülkeler daha mutlu ya da daha mutsuz olarak görülmektedir. Bununla birlikte, sadece mutluluğun ölçümüne odaklanmak yeterli değildir. Ülkelerin ekonomik, sosyal, siyasi ve kültürel faktörlerini de değerlendirmek gerekmektedir. Örneğin, ekonomik refah, sağlık, eğitim, adalet, özgürlük ve sosyal bağlar, mutluluğu artırmak için önemli faktörler olarak kabul edilmektedir. Günlük dilde refah, mutluluk ve memnuniyet gibi anlamlara taşısa da, felsefe ve psikoloji gibi teknik bağlamlarda farklı anlamlar içermektedir. Sosyal refah, bir kişinin yaşam kalitesini belirlemede yer alan faktörler veya unsurlar kümesini ifade eder ve nihayetinde, kişinin barışçıl bir varoluştan mahrum bırakılmadan, barışçıl bir varoluş sürdürmesine izin verir. Bu faktörler, ekonomik, sosyal ve kültürel yönleri içermekte olup, hemen hemen aynı şekilde etki gösterirler. Refahın adil bir biçimde sağlanabilmesi için dünyanın her yerindeki insanların hayata kalabilmesi için sosyal koruma altında bulunması gerekmektedir. Bazı ülkelerde, insanlar hayatlarını sürdürebilmeleri için gerekli olan temel ihtiyaçlara sahip değillerdir. Kimi yiyecek bulamazken kimi da sağlık, eğitim gibi temel ihtiyaçlardan yoksun kalmaktadırlar.Uluslararası mutluluk farklılıkları konusu, farklı ülkelerin farklı faktörlerle mutluluk seviyelerini nasıl etkilediğini ve mutluluğu artırmak için neler yapabileceğimizi anlamamıza yardımcı olacaktır.

## Çalışmanın Amacı
Dünya genelindeki ülkelerin mutluluk seviyeleri, gelir düzeyleri, eğitim seviyeleri, sağlık koşulları, sosyal faktörler ve kültürel farklılıklar gibi birçok değişkeni içermektedir. Bu veriler, istatistiksel analiz yöntemleri kullanılarak işlenerek farklı ülkelerin mutluluk seviyelerini etkileyen faktörlerin belirlenmesine yardımcı olabilir. Genel olarak, düşük bir gelir seviyesinin mutsuzluğa yol açacağı veya mutluluğun gelir seviyesi arttıkça aynı oranda artacağı beklentisi çalışmamızın sonucu olarak alınmıştır. Ancak bu görüş doğru değildir. Yüksek gelir grubuna ait ülkelerde bile mutluluk açısından yüksek puanlar alınamamaktadır. İnsani gelişme, yoksulluk, mutluluk ve bireysel refaha ilişkin verilerden hareketle, yoksul ülkeler arasında yapılan karşılaştırmalar sonucunda mutluluğun tamamen yaşam kalitesine bağlı bir olgu olarak değerlendirilemeyeceği sonucuna varabiliriz. Her ülkenin benimsediği refah sistemi farklıdır ve bireyler arasındaki ekonomik, sosyal ve cinsiyet açısından eşitsizliği gidermeyi amaçlayan bu hakların korunması konusunda farklı yaklaşımlar vardır. Bununla birlikte, birçok ülke bu hakların en az bir tanesi için benzer amaçlar taşımaktadır ve bu hakların ayrım gözetilmeksizin herkes için geçerli olması gerektiği konusunda hemfikirdir. Sonuç olarak, ülkelerin mutluluk seviyeleri üzerindeki etkisi incelenirken, yalnızca gelir seviyesi gibi tek bir değişkene odaklanmak yetersizdir. Farklı faktörlerin bir arada değerlendirilmesi gerekmektedir ve her ülkenin kendine özgü koşullarının dikkate alınması önemlidir.

## Literatür 
Daha İyi bir Yaşam için, vatandaşların toplumların refahını ölçme konusundaki tar- tışmalara katılmayı ve tüm yaşamlarımızı şekillendiren politika oluşturma sürecine daha bilinçli ve daha aktif olmalarını sağlamayı amaçlamaktadır. Özellikle 2000'lerden itibaren, refahın sadece gelir ile tanımlanması, bireylerin toplumların ve hatta ülkelerin gerçek refah seviyelerini yansıtmamaktadır. Bu endeks, refahı daha kapsamlı bir şekilde ele alarak, bireylerin mutlu oldukları alanları da hesaba katmaktadır. Ülkeler, bu endeks sayesinde geri kaldıkları alanları belirleyebilir ve bireylerin refahını maksimize edecek politikaları geliştirebilir. 


Çalışmaların büyük bir kısmı aileler ve bireyler üzerinde yoğunlaşmakta, kadının rolü ise genellikle görmezden gelinmektedir. Ancak, bu durum her devlet için geçerli değildir. Liberal rejimler, hizmet sunumunu piyasaya bırakarak cinsiyet ilişkilerine kayıtsız kalmaktadır[@wolff1992changing]. Bir deneyde, çocuklu çiftlerden oluşan benzersiz bir örneklem kullanılarak, boşanmış bireylerin evlilikten ayrıldıktan sonra ekonomik refahtaki cinsiyet farkını tahmin etmek amaçlanmıştır. Çalışan bireyler, ayrılmadan önce daha az cinsiyet farkı gördüklerini ifade etmişlerdir[@kuhn2020income]. Yaşam memnuniyeti ise hanehalkı geliri, yaş, cinsiyet, işgücü durumu ve eğitim durumu gibi faktörlerin bir fonksiyonu olarak gösterilebilir.


Bireylerin mutluluk düzeylerini açıklamada kullanılabilecek faktörler arasında, sağlık durumu, kentsel farklılıklar, bireylerin yaşadıkları döneme göre bakış açıları ve umutları yer almaktadır. Bir ekonomideki bireyler, hayatlarını sürdürmek için yeterli bir gelir elde etmek için emek, sermaye veya servetleriyle üretim sürecine katılmak zorunda kalabilirler. Ancak, sağlık sorunları, sakatlık, yaşlılık veya işsizlik gibi nedenlerle yeterli bir gelir elde etmek mümkün olmayabilir ve bireyler yeterli bir servet birikimi yapamayabilirler. Bu nedenle, devlet, kendi kusurları olmaksızın geçimlerini tamamen ya da kısmen sağlayamayan bireylerin yeterli bir gelire kavuşmalarını sağlayan yeniden dağıtım tedbirlerini almak zorundadır. Ekonomik süreç içerisinde fonksiyonel gelir dağılımı ile ilk olarak ortaya çıkan gelir, brüt gelirdir. Bu amaçla, devlet, gelir eşitsizliğini azaltmak için vergi sistemi ve sosyal güvenlik politikaları gibi tedbirler alır. Böylece, bireylerin yaşam memnuniyeti artar ve mutluluk düzeyleri yükselir[@kahyaouglu2008yacsam].


Kapitalist ekonomik sistem, yüksek gelir eşitsizliği gibi bazı sorunlarla karşı karşıya kalmaktadır ve bu sorunlar, zaman zaman insanların muhtaç durumda kalmasına neden olabilmektedir. Bu nedenle, refah devleti, gelir eşitsizliğini azaltmak ve insanlara onurlu bir yaşam sağlamak amacıyla ortaya çıkmıştır. Refah devleti, devletin müdahalesini gerektiren bir yapıya sahiptir ve muhtaç durumda kalan vatandaşlara en azından asgari yaşam standartı sağlamayı ve sosyal adaleti sağlamayı hedefler. Sosyal refah devleti uygulamaları, tüm ülkelerde dar anlamda uygulanmaktadır. Ancak geniş anlamda uygulamalar, daha kapsamlı bir yapı gerektirir ve geniş kaynaklar aktarılması gerekmektedir. Bu nedenle, bu çalışmada Türkiye'nin refah devleti uygulamalarının kapsamı ve etkinliği incelenmektedir. Mevcut eksikliklerin kaynakları ve planlanan gelişmeler açıklanarak, Türkiye'nin sosyal refah devleti uygulamalarında hangi noktalarda başarılı olduğu ve hangi alanlarda iyileştirme yapılması gerektiği ele alınmaktadır[@rakici2011refah].



\newpage
# Kaynakça {#references}
<div id="refs"></div>

